"""сreate_initial_tables

Revision ID: ed531726ca8f
Revises:
Create Date: 2026-08-06 07:28:53.514191

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ed531726ca8f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deliveries",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("product_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=50),
            server_default="processing",
            nullable=False,
            comment="Статус доставки: processing, delivery, completed, failed",
        ),
        sa.Column(
            "driver_id",
            sa.Uuid(),
            nullable=True,
            comment="ID водителя (случайное число)",
        ),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("address", sa.String(length=200), nullable=True),
        sa.Column("delivery_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deliveries_event_id"), "deliveries", ["event_id"], unique=True
    )
    op.create_index(
        "ix_deliveries_status_created_at",
        "deliveries",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deliveries_user_id"), "deliveries", ["user_id"], unique=False
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("complexity", sa.String(length=50), nullable=False),
        sa.Column("estimated_hours", sa.Float(), nullable=False),
        sa.Column("priority", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_task_id"), "reports", ["task_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reports_task_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_deliveries_user_id"), table_name="deliveries")
    op.drop_index("ix_deliveries_status_created_at", table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_event_id"), table_name="deliveries")
    op.drop_table("deliveries")
    # ### end Alembic commands ###
